---
- hosts: all
  become: yes
  tasks:
  - name: i want ping all nodes
    ping:

  - name: i want install git
    apt:
     name: git
    when: ansible_os_family=="Debian"


  - name: i want install tree
    apt:
     name: tree
    when: ansible_os_family=="Debian"

  - name: i want install webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: i want install webserver
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"
